processed 21 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-202:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "5N9uFYQrpet2xGo5KEck9UU684PNmSBb7mQt2scWdbiN",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "APssrYV8XKQoG5zErjnEhJKYRjITG52+4JN6f4N/JB2XiSmhs4P1ITad7JAaIdFgJ9CjuGg6tkG8+lO9IsF3LgB/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "4fFNLBxotLFvmxrbE5gq2vNhNzvAr6N5JKN9Hvn2rA89"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7315600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                    "digest": "FExb8WQJRbbqSL8K1hYdEnLZkABou1tJ9V55MaoBafRa"
                  }
                },
                {
                  "address": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382",
                    "digest": "2xo3wXG15PUKCCfatkgMjmtDJRWL1hUvAJUbgTGNa2Wy"
                  }
                },
                {
                  "address": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                    "digest": "2yjikxRPBaEojXnNofbt4yurNVmfiCjo3g3Vm2UNZhNB"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "5N9uFYQrpet2xGo5KEck9UU684PNmSBb7mQt2scWdbiN"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 204-222:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 224-224:
Checkpoint created: 2

task 6 'run-graphql'. lines 226-405:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "573Uuk3AeQFoZNHjxcdTNdovsR9g5WvdYu2c7NCL5pNS",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AExMrfvnijmU+cMAl9AAN4AKvSGnvmqOim7SrqQ7y5Mdy6q2kx1tRqQz3UkXMuKXX2f8QE9LOfHCupMppECqsgh/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                    "version": 2,
                    "digest": "2yjikxRPBaEojXnNofbt4yurNVmfiCjo3g3Vm2UNZhNB",
                    "object": {
                      "address": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                      "version": 2,
                      "digest": "2yjikxRPBaEojXnNofbt4yurNVmfiCjo3g3Vm2UNZhNB",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                            "package": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "4fFNLBxotLFvmxrbE5gq2vNhNzvAr6N5JKN9Hvn2rA89"
                },
                {
                  "digest": "5N9uFYQrpet2xGo5KEck9UU684PNmSBb7mQt2scWdbiN"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-4993420",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x6bad17539aef8bb79e763caac96cb9ae4fb2265fd1dd84f5e5f5ac739aa89596",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6bad17539aef8bb79e763caac96cb9ae4fb2265fd1dd84f5e5f5ac739aa89596",
                    "digest": "4xd6aSCn6M7BkpfqUGy5qefHMc6CM5eMqdTnhRMfDvaK"
                  }
                },
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                    "digest": "5W2xTkW6XZ2QV3L8hSz6xe7XUZKhVw8tGVQgXFettRVG"
                  }
                },
                {
                  "address": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd910063d3adb47bdaa744707682cdee69cc9116b0e58485479bbd43d6a8ed5eb",
                    "digest": "D5YHwKXwAc4tUrKmPJn5d9Genc57ycCu5REPgZtk7fPE"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "573Uuk3AeQFoZNHjxcdTNdovsR9g5WvdYu2c7NCL5pNS"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 407-410:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 412-421:
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'create-checkpoint'. lines 423-423:
Checkpoint created: 3

task 10 'run-graphql'. lines 425-613:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "8T5V8PEey3zAMCGuaRfLEZTcB7vTebbseSwxSc5P8yHP",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "APc8OO0DqdAHcmh/sdHWew60Ga7geQ8RmTAHRAddpYjVXa2+HZu6eI7i7NpLxPosI3kwyc6r6Nbx5nTdqB3HGQZ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x6bad17539aef8bb79e763caac96cb9ae4fb2265fd1dd84f5e5f5ac739aa89596",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x6bad17539aef8bb79e763caac96cb9ae4fb2265fd1dd84f5e5f5ac739aa89596",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x6bad17539aef8bb79e763caac96cb9ae4fb2265fd1dd84f5e5f5ac739aa89596",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "f2wh7Qx4MVRCUYrSS5CYr5K6HDspP8EPMxLKexSw7U7"
                },
                {
                  "digest": "573Uuk3AeQFoZNHjxcdTNdovsR9g5WvdYu2c7NCL5pNS"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3350680",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x46f56117378acd49eec1961cf429c91ab303850df00c15bb30b3c76e6303f1fc",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x46f56117378acd49eec1961cf429c91ab303850df00c15bb30b3c76e6303f1fc",
                    "digest": "CYiAuNMPF88hpkfkX6qsRB8h5U3nqJRUB8pTG9x4xz1F",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x46f56117378acd49eec1961cf429c91ab303850df00c15bb30b3c76e6303f1fc",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x7692aea565de4a0a3ba3346416db434cf5ec06f23eeb2502cd44a81c38af6922",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x7692aea565de4a0a3ba3346416db434cf5ec06f23eeb2502cd44a81c38af6922",
                    "digest": "7nif4s39woDxRTFw8fFwXwPHqbeHdjgPTmTH7XaPBMa3",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xcf837c16d9ca1cf4b4ba71bba72db7c3af28cf371fbce052d631458872a64382::m::Foo"
                        },
                        "json": {
                          "id": "0x7692aea565de4a0a3ba3346416db434cf5ec06f23eeb2502cd44a81c38af6922",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                    "digest": "6hRSAFiTmqonr6K8FgtCmXwoDBTUCbuCKDeNu853LUS4",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                          "balance": {
                            "value": "299999982036420"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "8T5V8PEey3zAMCGuaRfLEZTcB7vTebbseSwxSc5P8yHP"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11 'programmable'. lines 615-616:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12 'create-checkpoint'. lines 618-618:
Checkpoint created: 4

task 13 'run-graphql'. lines 620-799:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "D3PLwzQgv5DxFboUoHZR1JffS5yDWn9wyE7mkMvi36bT",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AIqtit82cKeRAu83+dmgaG024roERWWPeHxUhJiTaZrO/3eIWXszgsaHfTVk4hnkS5zRTTaSMACSkXxb2WyZ1gN/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "8T5V8PEey3zAMCGuaRfLEZTcB7vTebbseSwxSc5P8yHP"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1009880",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d",
                    "digest": "DyRww7e6cYyiodXdmCdUDr4XA7CNp2sq7NY4kqJGtRku"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xb39c4af52c00ef04fe18466e7717c7dceb60024491af9c6e7317ca2eb7b82c0d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "D3PLwzQgv5DxFboUoHZR1JffS5yDWn9wyE7mkMvi36bT"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 801-811:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJ0YyI6MH0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJ0YyI6MX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJ0YyI6NH0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 813-823:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJ0YyI6MH0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 825-835:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJ0YyI6MX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJ0YyI6NH0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17 'run-graphql'. lines 837-844:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18 'run-graphql'. lines 846-851:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJ0YyI6Mn0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        }
      ]
    }
  }
}

task 19 'run-graphql'. lines 853-858:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJ0YyI6M30"
        }
      ]
    }
  }
}

task 20 'run-graphql'. lines 860-870:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJ0YyI6M30"
        }
      ]
    }
  }
}
