processed 7 tasks

task 1 'publish'. lines 6-26:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 31-32:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 4 'programmable'. lines 34-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 5 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 6 'run-graphql'. lines 40-88:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xaecddcfd38335fb5ed32ada48ddba3e05b8810c527e230cbddf3697a28a5993c",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0x75b7fecccf63843c82dcb06d87e074bb8928258c6b1b28bfc7fbe1d13f60368e",
                  "version": 2,
                  "digest": "DnnVBAQVfxDEFgrZLk4YVv4PYqd8ZyY9s779KRxir5Yx",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xaecddcfd38335fb5ed32ada48ddba3e05b8810c527e230cbddf3697a28a5993c::m::Foo"
                        },
                        "json": {
                          "id": "0x75b7fecccf63843c82dcb06d87e074bb8928258c6b1b28bfc7fbe1d13f60368e",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xaecddcfd38335fb5ed32ada48ddba3e05b8810c527e230cbddf3697a28a5993c",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xaecddcfd38335fb5ed32ada48ddba3e05b8810c527e230cbddf3697a28a5993c",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xaecddcfd38335fb5ed32ada48ddba3e05b8810c527e230cbddf3697a28a5993c",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
