processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-38:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 40-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 4 'programmable'. lines 45-48:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 6 'programmable'. lines 52-56:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 58-58:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 62-62:
Checkpoint created: 4

task 10 'run-graphql'. lines 64-138:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                "value": "3"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                "value": "6"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                "value": "4"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                "value": "5"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                "value": "2"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                "value": "200"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x8ce5bbbe4fa35dca1c71b681cc9ba8c73a3863450da159d31bc59c4d6126cf35",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 140-184:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x8ce5bbbe4fa35dca1c71b681cc9ba8c73a3863450da159d31bc59c4d6126cf35",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x8ce5bbbe4fa35dca1c71b681cc9ba8c73a3863450da159d31bc59c4d6126cf35",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x8ce5bbbe4fa35dca1c71b681cc9ba8c73a3863450da159d31bc59c4d6126cf35",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 186-186:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 188-188:
Checkpoint created: 5

task 14 'run-graphql'. lines 190-264:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                "value": "3"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                "value": "6"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                "value": "4"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                "value": "5"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                "value": "2"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                "value": "200"
              },
              "type": {
                "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x8ce5bbbe4fa35dca1c71b681cc9ba8c73a3863450da159d31bc59c4d6126cf35",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 266-266:
Checkpoint created: 6

task 16 'run-graphql'. lines 268-303:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x31da17f8f9fdf9443e583d790b689b45d9e6ba321fc04cc873d4b51c5dda537b",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6b6b0b5f7b1b50e349c17a7b2c18adf13a3d0feeab3f4a9f425382a7a17c0016",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6c68017723c50bad3c104a39e5992598f7b8aa3b4cc83d3ca572ddbcbfbf9e5d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x97a9d9da5347b1e4db9da4790e75434dae916eaf02615f1e3063e80c7400608b",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc037feb1df6d7e3704a6cba90aed54cba329c76fad211d20cf10725913905bf1",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeec6b6a272139a301a0b7200e49428501ee0b401c1f40eae570dfaf92ee6f8fd",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x7dbc6861c6aeb0010c62404c29c531be7e96487746a1172e57728ed4bd1cd119::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
