processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 3 'run-graphql'. lines 40-88:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IAd98B5VOyuaLmuNfy5O4+GHw1ddEmij6wE8ltRHNiNSAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "ILOcSvUsAO8E/hhGbncXx9zrYAJEka+cbnMXyi63uCwNAQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IL5CZbNU9mu0Is6KfLhmsnplpS3Yty09s2DKm39dfFsuAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IBBgogriqeOjDzMa4O1VBrhqMdn6OInKKY5HF9FX7z4pAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x70d6371ebc59b01b065e450287847f3b0e536795f9c3361b6220ce894f00f6bb::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IBd+6hjHIfIAsr2Cq4eGhZKqgr/BdL8tzihz5dgYF6WKAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x70d6371ebc59b01b065e450287847f3b0e536795f9c3361b6220ce894f00f6bb::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IPwZ1o0ZdnxHE+UBArzYQHYzndGvavrJswhhsLYhmjCTAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x70d6371ebc59b01b065e450287847f3b0e536795f9c3361b6220ce894f00f6bb::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "ILOcSvUsAO8E/hhGbncXx9zrYAJEka+cbnMXyi63uCwNAQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHg3MGQ2MzcxZWJjNTliMDFiMDY1ZTQ1MDI4Nzg0N2YzYjBlNTM2Nzk1ZjljMzM2MWI2MjIwY2U4OTRmMDBmNmJiOjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x70d6371ebc59b01b065e450287847f3b0e536795f9c3361b6220ce894f00f6bb::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHg3MGQ2MzcxZWJjNTliMDFiMDY1ZTQ1MDI4Nzg0N2YzYjBlNTM2Nzk1ZjljMzM2MWI2MjIwY2U4OTRmMDBmNmJiOjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
