processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 44-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 48-48:
Checkpoint created: 1

task 4 'run-graphql'. lines 50-71:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  7,
                                  125,
                                  240,
                                  30,
                                  85,
                                  59,
                                  43,
                                  154,
                                  46,
                                  107,
                                  141,
                                  127,
                                  46,
                                  78,
                                  227,
                                  225,
                                  135,
                                  195,
                                  87,
                                  93,
                                  18,
                                  104,
                                  163,
                                  235,
                                  1,
                                  60,
                                  150,
                                  212,
                                  71,
                                  54,
                                  35,
                                  82
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988444520"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x077df01e553b2b9a2e6b8d7f2e4ee3e187c3575d1268a3eb013c96d447362352",
                          "balance": {
                            "value": "299999988444520"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x2e0bcc65d749c1de86ca8ec034e19657c148dbcb5341fec362bdb1bd88521b43::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  251,
                                  156,
                                  250,
                                  163,
                                  236,
                                  167,
                                  144,
                                  126,
                                  166,
                                  203,
                                  89,
                                  17,
                                  194,
                                  118,
                                  199,
                                  215,
                                  133,
                                  210,
                                  5,
                                  61,
                                  11,
                                  82,
                                  118,
                                  118,
                                  182,
                                  179,
                                  99,
                                  95,
                                  200,
                                  62,
                                  211,
                                  16
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  251,
                                  156,
                                  250,
                                  163,
                                  236,
                                  167,
                                  144,
                                  126,
                                  166,
                                  203,
                                  89,
                                  17,
                                  194,
                                  118,
                                  199,
                                  215,
                                  133,
                                  210,
                                  5,
                                  61,
                                  11,
                                  82,
                                  118,
                                  118,
                                  182,
                                  179,
                                  99,
                                  95,
                                  200,
                                  62,
                                  211,
                                  16
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      251,
                                      156,
                                      250,
                                      163,
                                      236,
                                      167,
                                      144,
                                      126,
                                      166,
                                      203,
                                      89,
                                      17,
                                      194,
                                      118,
                                      199,
                                      215,
                                      133,
                                      210,
                                      5,
                                      61,
                                      11,
                                      82,
                                      118,
                                      118,
                                      182,
                                      179,
                                      99,
                                      95,
                                      200,
                                      62,
                                      211,
                                      16
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xfb9cfaa3eca7907ea6cb5911c276c7d785d2053d0b527676b6b3635fc83ed310",
                          "f0": "0xfb9cfaa3eca7907ea6cb5911c276c7d785d2053d0b527676b6b3635fc83ed310",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xfb9cfaa3eca7907ea6cb5911c276c7d785d2053d0b527676b6b3635fc83ed310"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
